### ISSUE TITLE
KeyError: 'always_verify_hash'

### ISSUE THREAD

**Issue by newadventure079** [JohnDoee/autotorrent2#11]
`at2 -v add rtorrent torrents/tmp/test.torrent`
```
DEBUG:libtc.clients.rtorrent:41:Creating Normal XMLRPC Proxy with url http://172.17.0.1:10004/RPC2
Matching 1 torrent
DEBUG:autotorrent.db:174:Doing query: 'SELECT name, path, size, normalized_name, unsplitable_root FROM files WHERE normalized_name = ? AND size = ?' with args: ['[clips4sale com]myawesomemother1080.mp4', 1151009539]
DEBUG:autotorrent.utils:307:Piece calculation start_piece: 0 start_offset: 0 first_complete_piece: 0 end_piece: 1097 end_offset: 721667 last_complete_piece: 1096
Traceback (most recent call last):
  File "/var/services/homes/me/.autotorrent/bin/at2", line 8, in <module>
    sys.exit(cli())
  File "/var/services/homes/me/.autotorrent/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/var/services/homes/me/.autotorrent/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/var/services/homes/me/.autotorrent/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/services/homes/me/.autotorrent/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/var/services/homes/me/.autotorrent/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/var/services/homes/me/.autotorrent/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/var/services/homes/me/.autotorrent/lib/python3.8/site-packages/autotorrent/__main__.py", line 446, in add
    ctx.obj["always_verify_hash"], match_result.matched_files
KeyError: 'always_verify_hash'
```

**Comment by JohnDoee** [comment]
Added in 1.0.2
