### ISSUE TITLE
Error During Setup

### ISSUE THREAD

**Issue by mesol86** [JohnDoee/autotorrent2#22]
Hi, I got this error message when run "python -m autotorrent test-connection". What will be the best next step to debug?

```
Traceback (most recent call last):
  File "C:\Python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python\lib\site-packages\autotorrent\__main__.py", line 750, in <module>
    cli()
  File "C:\Python\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Python\lib\site-packages\click\core.py", line 1654, in invoke
    super().invoke(ctx)
  File "C:\Python\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Python\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Python\lib\site-packages\autotorrent\__main__.py", line 176, in cli
    ctx.obj.update(parse_config_file(config, utf8_compat_mode=utf8_compat_mode))
  File "C:\Python\lib\site-packages\autotorrent\__main__.py", line 77, in parse_config_file
    config = toml.load(path)
  File "C:\Python\lib\site-packages\toml\decoder.py", line 134, in load
    return loads(ffile.read(), _dict, decoder)
  File "C:\Python\lib\site-packages\toml\decoder.py", line 340, in loads
    raise TomlDecodeError("Unbalanced quotes", original, i)
toml.decoder.TomlDecodeError: Unbalanced quotes (line 66 column 47 char 2304)
```

**Comment by newadventure079** [comment]
You probably have unbalanced quotes in your config file
