### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by newadventure079** [JohnDoee/autotorrent2#24]
```
Traceback (most recent call last):
  File "/var/services/homes/me/.autotorrent/bin/at2", line 8, in <module>
    sys.exit(cli())
  File "/var/services/homes/me/.autotorrent/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/var/services/homes/me/.autotorrent/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/var/services/homes/me/.autotorrent/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/services/homes/me/.autotorrent/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/var/services/homes/me/.autotorrent/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/var/services/homes/me/.autotorrent/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/var/services/homes/me/.autotorrent/lib/python3.8/site-packages/autotorrent/__main__.py", line 477, in add
    match_result = matcher.match_files_dynamic(
  File "/var/services/homes/me/.autotorrent/lib/python3.8/site-packages/autotorrent/matcher.py", line 265, in match_files_dynamic
    self._select_best_candidate(
  File "/var/services/homes/me/.autotorrent/lib/python3.8/site-packages/autotorrent/matcher.py", line 162, in _select_best_candidate
    return sorted(
IndexError: list index out of range
```
I dont really have any other info to provide.  It was going along and spit this out in the same spot each time. I dont know what torrent it was on because I think it only shows the name after it's been processed

**Comment by newadventure079** [comment]
It might be due to `add_limit_percent = 100`.  I had it at 100 and it happened each time. I changed it to 99 and it didn't error

**Comment by JohnDoee** [comment]
It probably thinks there's a match when all files are missing, since that's what `add_limit_percent = 100` so should be easy to fix.
