### ISSUE TITLE
test-connection fail

### ISSUE THREAD

**Issue by SoberAddiction** [JohnDoee/autotorrent2#38]
installed with python3.8. I think my config is right, but I cannot test the connection to rutorrent. rutorrent is in docker while auttotorrent2 is not. Would like to run this in docker, but i'm not smart enough yet.

Traceback (most recent call last):
  File "/home/home/.autotorrent/lib/python3.10/site-packages/toml/decoder.py", line 511, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
  File "/home/home/.autotorrent/lib/python3.10/site-packages/toml/decoder.py", line 778, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "/home/home/.autotorrent/lib/python3.10/site-packages/toml/decoder.py", line 880, in load_value
    return (self.load_array(v), "array")
  File "/home/home/.autotorrent/lib/python3.10/site-packages/toml/decoder.py", line 1026, in load_array
    nval, ntype = self.load_value(a[i])
  File "/home/home/.autotorrent/lib/python3.10/site-packages/toml/decoder.py", line 910, in load_value
    raise ValueError("This float doesn't have a leading "
ValueError: This float doesn't have a leading digit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/home/.autotorrent/bin/at2", line 8, in <module>
    sys.exit(cli())
  File "/home/home/.autotorrent/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/home/.autotorrent/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/home/.autotorrent/lib/python3.10/site-packages/click/core.py", line 1654, in invoke
    super().invoke(ctx)
  File "/home/home/.autotorrent/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/home/.autotorrent/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/home/.autotorrent/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/home/.autotorrent/lib/python3.10/site-packages/autotorrent/__main__.py", line 182, in cli
    ctx.obj.update(parse_config_file(config, utf8_compat_mode=utf8_compat_mode))
  File "/home/home/.autotorrent/lib/python3.10/site-packages/autotorrent/__main__.py", line 82, in parse_config_file
    config = toml.load(path)
  File "/home/home/.autotorrent/lib/python3.10/site-packages/toml/decoder.py", line 134, in load
    return loads(ffile.read(), _dict, decoder)
  File "/home/home/.autotorrent/lib/python3.10/site-packages/toml/decoder.py", line 514, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: This float doesn't have a leading digit (line 9 column 1 char 135)

**Comment by Kha-kis** [comment]
@SoberAddiction I am having this same issue.
How did you resolve it?

**Comment by Kha-kis** [comment]
For anyone else who may run into this issue.
I was able to resolved the following error message by ensuring that the paths set were enclosed with quotes "":

"This float doesn't have a leading digit (line 9 column 1 char 135)"

**Comment by TiarnanRedmond** [comment]
I have the same issue. When I try to install and run `at2 check-config` it gives this error:

```Traceback (most recent call last):
  File "/home/user/.autotorrent/lib/python3.9/site-packages/toml/decoder.py", line 511, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
  File "/home/user/.autotorrent/lib/python3.9/site-packages/toml/decoder.py", line 778, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "/home/user/.autotorrent/lib/python3.9/site-packages/toml/decoder.py", line 880, in load_value
    return (self.load_array(v), "array")
  File "/home/user/.autotorrent/lib/python3.9/site-packages/toml/decoder.py", line 1026, in load_array
    nval, ntype = self.load_value(a[i])
  File "/home/user/.autotorrent/lib/python3.9/site-packages/toml/decoder.py", line 849, in load_value
    raise ValueError("Found tokens after a closed " +
ValueError: Found tokens after a closed string. Invalid TOML.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.autotorrent/bin/at2", line 8, in <module>
    sys.exit(cli())
  File "/home/user/.autotorrent/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.autotorrent/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/user/.autotorrent/lib/python3.9/site-packages/click/core.py", line 1654, in invoke
    super().invoke(ctx)
  File "/home/user/.autotorrent/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.autotorrent/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/.autotorrent/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/.autotorrent/lib/python3.9/site-packages/autotorrent/__main__.py", line 182, in cli
    ctx.obj.update(parse_config_file(config, utf8_compat_mode=utf8_compat_mode))
  File "/home/user/.autotorrent/lib/python3.9/site-packages/autotorrent/__main__.py", line 82, in parse_config_file
    config = toml.load(path)
  File "/home/user/.autotorrent/lib/python3.9/site-packages/toml/decoder.py", line 134, in load
    return loads(ffile.read(), _dict, decoder)
  File "/home/user/.autotorrent/lib/python3.9/site-packages/toml/decoder.py", line 514, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: Found tokens after a closed string. Invalid TOML. (line 9 column 1 char 132)
```

I checked the line 9 on the file /.autotorrent/lib/python3.9/site-packages/toml/decoder.py but couldn't see anything weird to me. Probably I'm not looking in the right place. Could anyone please help me to resolve this?
