### ISSUE TITLE
KeyError: 'same_paths'

### ISSUE THREAD

**Issue by newadventure079** [JohnDoee/autotorrent2#4]
`at2 check-config`
```
Traceback (most recent call last):
  File "/var/services/homes/me/.autotorrent/bin/at2", line 8, in <module>
    sys.exit(cli())
  File "/var/services/homes/me/.autotorrent/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/var/services/homes/me/.autotorrent/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/var/services/homes/me/.autotorrent/lib/python3.8/site-packages/click/core.py", line 1654, in invoke
    super().invoke(ctx)
  File "/var/services/homes/me/.autotorrent/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/var/services/homes/me/.autotorrent/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/var/services/homes/me/.autotorrent/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/var/services/homes/me/.autotorrent/lib/python3.8/site-packages/autotorrent/__main__.py", line 128, in cli
    ctx.obj.update(parse_config_file(config, utf8_compat_mode=utf8_compat_mode))
  File "/var/services/homes/me/.autotorrent/lib/python3.8/site-packages/autotorrent/__main__.py", line 53, in parse_config_file
    parsed_config["rewriter"] = rewriter = PathRewriter(parsed_config["same_paths"])
KeyError: 'same_paths'
```

**Comment by JohnDoee** [comment]
I've made the option optional in release 1.0.1.
