### ISSUE TITLE
Very weird error when scanning directory

### ISSUE THREAD

**Issue by Yankees4life** [JohnDoee/autotorrent2#50]
Not too sure whats happening here. I'm using python 3.11 BTW

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python311\Scripts\at2.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\click\core.py", line 1654, in invoke
    super().invoke(ctx)
  File "C:\Program Files\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\autotorrent\__main__.py", line 182, in cli
    ctx.obj.update(parse_config_file(config, utf8_compat_mode=utf8_compat_mode))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\autotorrent\__main__.py", line 84, in parse_config_file
    parsed_config.update(config["autotorrent"])
                         ~~~~~~^^^^^^^^^^^^^^^
KeyError: 'autotorrent'
```

**Comment by Yankees4life** [comment]
I'm an idiot. Looked like an encoding error. Switched to Powershell (the open source one) and it worked.
