### ISSUE TITLE
KeyError: 'rw_file_cache_path'

### ISSUE THREAD

**Issue by newadventure079** [JohnDoee/autotorrent2#6]
In the config template is says `Config settings for the RW cache if enabled`.  I dont have RW cache enabled so I removed those 3 entries but now it complains I dont have `rw_file_cache_path` specified

`at2 check-config`
```
Traceback (most recent call last):
  File "/var/services/homes/.autotorrent/bin/at2", line 8, in <module>
    sys.exit(cli())
  File "/var/services/homes/.autotorrent/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/var/services/homes/.autotorrent/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/var/services/homes/.autotorrent/lib/python3.8/site-packages/click/core.py", line 1654, in invoke
    super().invoke(ctx)
  File "/var/services/homes/.autotorrent/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/var/services/homes/.autotorrent/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/var/services/homes/.autotorrent/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/var/services/homes/.autotorrent/lib/python3.8/site-packages/autotorrent/__main__.py", line 143, in cli
    ctx.obj.update(parse_config_file(config, utf8_compat_mode=utf8_compat_mode))
  File "/var/services/homes/.autotorrent/lib/python3.8/site-packages/autotorrent/__main__.py", line 73, in parse_config_file
    parsed_config["rw_file_cache_path"],
KeyError: 'rw_file_cache_path'
```

**Comment by JohnDoee** [comment]
Fixed in 1.0.2, thanks for reporting these !
