### ISSUE TITLE
Error on torrent add: KeyError: 'create_subfolder_enabled'

### ISSUE THREAD

**Issue by Tr4il** [JohnDoee/autotorrent2#9]
Adding a torrent to my qbittorrent instance gives me the following:
```Matching 1 torrent
Traceback (most recent call last):
  File "/home/user/.autotorrent/bin/at2", line 8, in <module>
    sys.exit(cli())
  File "/home/user/.autotorrent/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.autotorrent/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/user/.autotorrent/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.autotorrent/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.autotorrent/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/.autotorrent/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/.autotorrent/lib/python3.10/site-packages/autotorrent/__main__.py", line 521, in add
    client.add(
  File "/home/user/.autotorrent/lib/python3.10/site-packages/libtc/clients/qbittorrent.py", line 137, in add
    create_subfolder_enabled = self._check_create_subfolder_enabled()
  File "/home/user/.autotorrent/lib/python3.10/site-packages/libtc/clients/qbittorrent.py", line 117, in _check_create_subfolder_enabled
    return self.call("get", "/api/v2/app/preferences").json()[
KeyError: 'create_subfolder_enabled'
```

The link does get made and the file is accessible there, but it does not get added to the client.
I have the subfolder setting in qBittorrent set to "Original", if that matters?
Thanks!

**Comment by JohnDoee** [comment]
Without that option you cannot actually know where qBittorrent will download data when you add it. They didn't get around to adding the preference until around end of 2018.

Which version of qBittorrent are you running?

**Comment by JohnDoee** [comment]
It's not related to anything you do, it's about if torrents are saved to a folder with the same name as the torrent or not.

qBittorrent team modified how the option works without any warning and did not document it anywhere.

**Comment by JohnDoee** [comment]
This should work now with all versions of qBittorrent I could get my hand on easily in 1.0.3.
